// Student writing from Jubilee School honoring people connected to Eden Cemetery.
// Transcribed faithfully from the students' documents. Bylines appear as the students wrote them.
export const JUBILEE_CREDIT = 'Jubilee School, Philadelphia — students in grades 2 through 8, with alumni';

export const JUBILEE = [
 {
  id: 'still', name: 'William Still', dates: '1821 – 1902', onNotables: true,
  students: 'By Connor, Anela, Aasimah and Nahla',
  intro: `William Still was a brilliant, liberating man who did amazing things to help enslaved people reach freedom. He made sure that when enslaved people ran away to freedom they had a safe place to stay. William wrote down stories of escaped fugitives so he could reunite families separated by slavery. He kept himself out of the spotlight and told the fugitives’ stories. William Still should forever be remembered in the heart of history.`,
  story: [
   `William Still was a brilliant, liberating man who did amazing things to help enslaved people reach freedom. He didn’t just free people from slavery, he freed their hearts from the horror and pain that came with it. He was an activist. Some people even called him the Father of the Underground Railroad. He made sure that when enslaved people ran away to freedom they had a safe place to stay. He helped around 800 people escape from slavery to freedom, and lost very few. William wrote down stories of escaped fugitives so he could reunite families separated by slavery. He kept himself out of the spotlight and told the fugitives’ stories.`,
   `William Still was born in Medford, New Jersey in 1821. His parents had been enslaved until his father bought his freedom in 1798. His mother escaped two times, the second time in the middle of the night, leaving her two sons and taking her two daughters. After escaping she reunited with her husband in New Jersey.`,
   `When they escaped, William Still’s mother Sydney changed her name to Charity and her husband, Levin, changed their last name from Steel to Still to protect themselves from people who wanted to return them to the slave masters. In New Jersey, Charity had fourteen more children. William was the last of eighteen children. At a very young age William taught himself to read and write by reading books. He worked with his father on a farm to make ends meet.`,
   `After a period of time, in 1844, William Still moved to Philadelphia. In 1847 he got married to Letitia George and ended up joining the Pennsylvania Society for the Abolition of Slavery. In 1850 the Fugitive Slave Act was put into action, which meant that if you were helping an enslaved person to escape you could be held accountable and put into prison and you’d have to pay a fine. It meant that those who escaped and everyone that helped them could be captured. Because of this act the Pennsylvania Society for the Abolition of Slavery created the Vigilance Committee. William Still was the chairman; that meant he would guide people safely on the Underground Railroad through Philadelphia to Canada.`,
   `Henry Box Brown was a man who shipped himself to freedom. This man sent himself to William Still’s office in Philadelphia in a wooden crate to escape slavery. The box was labeled as dry goods and marked “This side up”. But for half of the trip he was upside down, despite the label on the box. Henry Box Brown traveled on five different modes of transportation: ferry, steamboat, delivery wagon, a cart and the railroad. This trip took twenty seven hours. All he had to eat was a few biscuits and some water. When he arrived in Philadelphia William Still and three other people opened the box and Brown popped up and said “How do you do, gentleman?” and started to sing “I waited patiently for the Lord and he heard my prayer.”`,
   `Two enslaved people thought that the only way out of slavery was to ship themselves in a box to freedom. One of the two was Henry Box Brown and he ended up getting all of the fame. But the woman hidden behind Henry’s shadow was Lear Green, the woman who shipped herself in a crate almost a decade before Henry. This brave and daring woman chose to ship herself in a sailor’s chest to have the right to bear free children and to marry the love of her life, a free Black man named William Adams. Adams’ mother risked her life to help Lear Green escape from slavery in a sailor’s chest checking the box frequently for eighteen hours from Maryland to Pennsylvania. In Philadelphia they ended up meeting William Still, the “Father of the Underground Railroad”. Then they moved farther North to pursue their dream of getting married. Green lived a happy life as a married woman for three years, but sadly she died at the age of twenty-one. Lear Green died knowing that there was a man who loved her as much as she loved him.`,
   `Peter Freedman came to Philadelphia in 1850 to find his family. He went to the house of Eliza and James Bias. Eliza found a guide to take him to William Still at the Pennsylvania Anti-Slavery Office. On the way there, Peter thought that his parents wouldn’t recognize him after forty years, which filled him with anxiety and worry. When he got there he told his story to William Still. When Peter told his story the names of his parents, Levin and Sydney, caught William’s ear. The thing that solidified his belief that they were brothers was that forty years ago Peter and his brother had been separated from their mother and sisters, and that was William’s mother’s story. William was so glad that he had finally found his lost brother that he decided that everyone who lost family should have that feeling so he chose to document the stories of every fugitive who passed through his office so they could find their families as well.`,
   `William Still kept meticulous notes on the fugitives who fled slavery. Recording the stories was dangerous because it was evidence of his involvement in the Underground Railroad. At the time the Fugitive Slave Act said that if you were an escaped slave you’d get sent back to the plantation. But Still kept the notes anyway to the benefit of many. After the Civil War he published these stories in a book called “The Underground Railroad: A Record of Facts, Authentic Narratives, Hairbreadth Escapes and Death of Slaves and Their Effort of Freedom Struggles as Related by Themselves and Others, or Witnessed by the Author…”. This let unheard voices be heard and spread to places they wouldn’t have reached otherwise. William wrote this because of his experience with his brother. That experience led him to realize how great it is to find lost relatives, so he made it so other people could experience the same feeling he did.`,
   `William Still was an extraordinary man for how he helped enslaved families and people on their journey to freedom. After everything he did he should not be forgotten. William Still should forever be remembered in the heart of history.`
  ],
  letter: null,
  poems: [
   { title: 'William Still, Our Beloved Hero', by: 'Adria and Tiana', lines: ['William,', 'A brave and strong man,', 'Gliding on the cusp of slavery.', '', 'William,', 'Saving his fellow children,', 'One by one.', '', 'William,', 'Writing through his pain,', 'Making his voice heard.', '', 'William,', 'Our hero,', 'Guiding us out of slavery.'] },
   { title: 'Freedom Fighter', by: 'Shanah, Mason and Benjamin', lines: ['The black mastermind', 'Plotting against slavery', 'Our freedom fighter.', '', 'Born as a free bird', 'Free man fighting for justice', 'Our freedom tiger.'] },
   { title: 'A Mark So Bright', by: 'Benjamin', lines: ['He’s a strong Black man', 'Leaving his mark on the world', 'A mark so bright it outshines the sun.'] }
  ]
 },
 {
  id: 'catto', name: 'Octavius Catto', dates: '1839 – 1871', onNotables: true,
  students: 'By Yasir, grade 5 — poems by Priscilla, Morgan and Felix',
  intro: `Octavius Catto, the “Forgotten Hero”, was an educator and Civil Rights activist in the 1800s. Catto fought for voting rights and for African American people to ride public transportation. Catto thought African American people should be heard so he fought his best. Catto was not only fighting against segregation, he was also fighting for equal rights. He was trying to get Black people to vote, and not be terrorized by white people.`,
  story: [
   `Octavius Catto, the “Forgotten Hero”, was on a horse-drawn rail car in Philadelphia on May 18, 1855. The conductor requested multiple times for Catto to leave the railcar because transportation in Philadelphia was segregated at that time. Catto refused to get off the trolley. When Catto would not get off the conductor railed the car and detached the horses so Catto would be the only one left in the railcar. Catto actually spent the night in the trolley. It inspired other Black people to challenge the rules. The year after that there was an important meeting at the Urban League and Catto presented multiple flaws in the system. He also asked for help in his quest for justice.`,
   `After the Civil War Catto became a civil rights person on the state level. It was the summer of 1865 when more and more people protested about Black people not being able to go on street cars. So Catto went to work to stop segregation. In 1867 Catto succeeded and a law was made that you could not segregate street cars. Three days after the law was passed Catto’s fiancé, Caroline LeCount, was refused passage on a trolley and then the conductor was fired and arrested.`,
   `Catto was not only fighting against segregation, he was also fighting for equal rights. He was trying to get Black people to vote, and not be terrorized by white people. On election day, October 10, 1871, Catto was on his way to vote when he was shot three times by Frank Kelley, a white democrat and the bullet wounds were fatal. Catto was a respectful man to the Black community and he fought for Black people’s justice. He made equal rights possible.`
  ],
  letter: null,
  poems: [
   { title: 'A Soldier of Words', by: 'Priscilla', lines: ['Octavius Catto was like a diamond', 'strong but inspiring.', 'He was like a tree', 'that would not move until there was peace.', 'He was a voice that spoke for the people', 'who could not speak for themselves.', 'He was like a soldier of words.'] },
   { title: 'The Forgotten Hero', by: 'Morgan', lines: ['The forgotten hero', 'Someone to remember through the caves of history.', 'Someone as a spirit for one hundred years', 'Trying to fight racism.', 'To live in life with dark', 'He is one of the lights', 'An immovable human being.'] },
   { title: 'A Soul of Bravery', by: 'Felix', lines: ['Catto was a soul of bravery', 'Strong as a mountain and stiff as can be.', 'He assisted freedom massively', 'Single-handedly.', 'Still his life was short', 'But he accomplished many things.', 'The forgotten hero.'] }
  ]
 },
 {
  id: 'lecount', name: 'Caroline LeCount', dates: '1846 – 1923', onNotables: true,
  students: 'By Jubilee School students',
  intro: `Caroline LeCount was an amazing woman advocating for Black rights and for Black students to have a good education. She was a teacher then a principal for a school for African American students. Caroline LeCount, Octavius Catto, William Still and others fought for the right for Black people to ride public transportation.`,
  story: [
   `Caroline LeCount was an amazing woman advocating for Black rights and for Black students to have a good education. She was a teacher then a principal for a school for African American students called the Ohio Street School in Philadelphia. Her father was involved in the Underground Railroad so she was around advocacy all of her life. Caroline LeCount, Octavius Catto, William Still and others fought for the right for Black people to ride public transportation. Three days after the law got passed, Caroline was trying to get on a streetcar. Because the streetcar driver wouldn’t let her get on, she called the police. At first the police did not believe the law had changed, so Caroline showed him a copy of the law and the policeman finally arrested the driver.`,
   `Caroline was engaged to Octavius Catto, but sadly he was brutally assassinated for fighting for Black suffrage. After Catto got murdered, Caroline named her school after her fiancé.`
  ],
  letter: [`Dear Caroline LeCount,`, `You are one of the many people responsible for giving Black people fairness and rights. You cared about our community. You ripped pages of hard times into hope for freedom. You provided education for African Americans in Philadelphia. You helped Black people get on public transportation without getting kicked off. You showed that we can put our word out for our community and fight for a new chapter of freedom. You showed greatness to Philadelphia. Thank you for bringing us hope.`],
  poems: []
 },
 {
  id: 'anderson', name: 'Marian Anderson', dates: '1897 – 1993', onNotables: true,
  students: 'By Nyla, grade 6',
  intro: `Marian Anderson was an African American woman with a beautiful singing voice. She believed in Black pride and didn’t let prejudice get in the way of her career. Much of Marian’s life would consist of breaking down barriers for African American performers.`,
  story: [
   `Marian Anderson was an African American woman with a beautiful singing voice. She believed in Black pride and didn’t let prejudice against her skin color get in the way of her career. She was a smart, confident Christian woman and her story starts here.`,
   `Marian was born February 27, 1897 in Philadelphia. She was the oldest of three girls and was six when she became a part of the choir at Union Baptist Church, where she earned the nickname “Baby Contralto”. Members of the church raised money for her to attend music school for one year. Her father supported his daughter’s musical interests and when Anderson was eight she got her first piano. Her parents weren’t able to afford lessons, so she taught herself.`,
   `At the age of twelve Marian’s father died, leaving her mother to raise three young girls. His death didn’t affect Marian’s musical ambitions or her singing with the church choir. She rehearsed all the songs and instruments in front of her family until she perfected them.`,
   `Marian’s commitment to her music and power as a singer impressed her choir so much that they came together and raised five hundred dollars for her to train under Guiseppe Boghetti, a respected voice teacher.`,
   `In the late 1930’s Marian’s voice made her well known on both sides of the Atlantic. She was invited to the White House by President Roosevelt and his wife Eleanor for a performance. She was the first African American ever to receive this honor.`,
   `Much of Marian’s life would consist of breaking down barriers for African American performers. For example, the gifted contralto singer became the first African American to perform at the New York Metropolitan Opera.`,
   `Despite her success not all of America received Marian’s talent. In 1939 her manager tried to set up a show for her at Washington, DC’s Constitution Hall, but unfortunately no dates were available. But that was far from the truth. The only reason they lied and declined was because the D.A.R. (Daughters of the American Republic) committed the hall to be strictly for white performers. When the situation leaked out to the public, Eleanor Roosevelt invited Marian to perform at the Lincoln Memorial on Easter Sunday. Marion took the offer, performed in front of 75,000 people and it was live broadcasted for millions of radio listeners.`,
   `Marian’s popularity and fame grew over the next several decades of her life. In 1961 she sang the National Anthem at President JFK’s inauguration. Two years later she was honored with the Presidential medal of Freedom.`,
   `After her retiring in 1965 Marian set up a new life for herself. In 1991 the music world honored her with a Grammy Award for Lifetime Achievement. Her final years were spent in Portland, Oregon, where she moved in with her nephew and died of natural causes on April 8, 1993.`
  ],
  letter: null,
  poems: [
   { title: 'Her Voice', by: 'Jubilee School students', lines: ['She was rich in knowledge', 'and Black beauty', 'her voice', 'like a bird singing in the morning', 'her songs', 'shining glowing stars', 'her voice', 'a butterfly that makes joy', 'and never stops flying', 'her power', 'independence that burned brighter', 'than a supernova', 'her voice', 'gave power to the people'] }
  ]
 },
 {
  id: 'harper', name: 'Frances Ellen Watkins Harper', dates: '1825 – 1911', onNotables: true,
  students: 'By Jubilee School students',
  intro: `This woman was a powerful woman with powerful words and her voice shines bright like a diamond. This woman’s name is Frances Ellen Watkins Harper. Frances wrote poetry and novels. She wrote thirteen books and was still writing at the age of seventy-five. Frances worked in the Underground Railroad, the Women’s Suffrage Movement, the American Anti-Slavery Society, the Abolitionist Movement and the Temperance Movement. She fought for justice and many causes throughout her life.`,
  story: [
   `This woman was a powerful woman with powerful words and her voice shines bright like a diamond. This woman’s name is Frances Ellen Watkins Harper. She refused to get off her seat on a railroad car because white passengers needed the seat. This is what she said: “I have been insulted on several railroad cars. The other day, in attempting to ride in one of the city cars, after I had entered, the conductor came to me, and wanted me to go out on the platform… I did not move, but kept the same seat. When I was about to leave, he refused my money, and I threw it down on the car floor, and got out, after I had ridden as far as I wished. Such impudence!” She got off the railroad car with victory in her hands.`,
   `Frances Watkins Harper was born on September 24, 1825 and when she was three her mother died and she didn’t have a father. She moved in with her aunt and uncle, and went to her uncle’s school, the Academy of Negro Youth. After she grew up, she got a job as a seamstress.`,
   `Frances wrote poetry and novels. She was inspired by her getting asked to move from the train to write a poem called “Bury Me in a Free Land”. Her first book of poems was published in 1845 and it was called “Forest Leaves”. She wrote thirteen books and was still writing at the age of seventy-five.`,
   `Frances worked in the Underground Railroad, the Women’s Suffrage Movement, the American Anti-Slavery Society, the Abolitionist Movement and the Temperance Movement. She fought for justice and many causes throughout her life.`
  ],
  letter: null,
  poems: [
   { title: 'Sturdy as the Eiffel Tower', by: 'Jubilee School students', lines: ['She was sturdy as the Eiffel Tower', 'she led a lifetime of hope', 'writing truth with her words.', 'And those words', 'were as powerful as thunder', 'and the thunder was eternal.'] },
   { title: 'To My Ancestor', by: 'Queen Mother Falaka Fattah, to her ancestor Frances Ellen Watkins Harper', lines: ['I am you', 'and you are me', 'and we are one together.'] }
  ]
 },
 {
  id: 'forten', name: 'James Forten', dates: '1766 – 1842', onNotables: true,
  students: 'By Morgan, Mason, Anela (alumni); Minna, Miles, Deyvon, Key’ier, Joshua, Marabella, Theo and Khaseem (grades 2–5)',
  intro: `James Forten was a very intelligent man. He wanted for slavery to be abolished. He wanted the Declaration of Independence be applied and that everybody be treated equally. He fought for the rights of African Americans. He made a lot of money, becoming one of the richest men in Philadelphia. He hired Black and white people to create an equal work environment. Not only was he loyal to his country, but he used his wealth to help the Black community and to set the standards for equality. James Forten was one of the many powerful voices for freedom from slavery.`,
  story: [
   `James Forten was a very intelligent man. He wanted for slavery to be abolished. He wanted the Declaration of Independence be applied and that everybody be treated equally. He fought for the rights of African Americans.`,
   `James Forten was on a ship during the Revolutionary War. The British attacked the ship. They took James Forten and tried to bring him to England but he refused to go because he wanted to prove his loyalty to America. When he refused he was sent to prison. He could have been sold into slavery.`,
   `When James Forten returned to America he bought his father’s sail-making business. He made a lot of money, becoming one of the richest men in Philadelphia. He hired Black and white people to create an equal work environment. Not only was he loyal to his country, but he used his wealth to help the Black community and to set the standards for equality. James Forten was one of the many powerful voices for freedom from slavery. He campaigned for many things; mainly African American rights.`
  ],
  letter: [`Dear James Forten,`, `You were like a mirror that reflected loyalty.`, `You were a black hole that swallowed terrible times.`, `You were a hero in your own kind of way.`, `You wanted slavery to end; you wanted equality for Black people.`, `Your spirit was strong and you had hope.`, `You were brave like a lion that showed hope to the Black community.`, `You were like a sail that crossed the ocean with knowledge and equality.`],
  poems: []
 },
 {
  id: 'whipper', name: 'William Whipper', dates: '1804 – 1876', onNotables: true,
  students: 'By Morgan & Jayla, grades 7 & 8 (alumni); Joshua & Minna, grade 4',
  intro: `William Whipper was a great man. He transported enslaved people from the South to the North. He fought non-violently for Black voting rights. He had the same ideas about protesting non-violently as Dr. King, but his ideas were less appreciated because of the times.`,
  story: [
   `William Whipper was a great man. He transported enslaved people from the South to the North. He fought non-violently for Black voting rights. He had the same ideas about protesting non-violently as Dr. King, but his ideas were less appreciated because of the times.`,
   `William was owned by his father because his mother was enslaved to his father. He was well educated growing up, which made him the person he was. He was very interesting, and he always had the passion to fight for fairness for Black people. He was financially well off because he was partners with his brother-in-law in a lumber business. He used the compartments in the lumber trains to hide enslaved people and bring them to freedom. He used his money to help enslaved people by giving them hope and liberty.`
  ],
  letter: null,
  poems: [
   { title: 'Ode to William Whipper', by: 'Morgan, Jayla, Miles, Theo, Bella, Josh, Minna', lines: ['William Whipper', 'a lamp in the dark', 'warmth in the cold', 'an umbrella in the rain', 'an eagle calling out for liberty', 'a hummingbird singing songs of freedom', '', 'William Whipper', 'a brave man welcoming people', 'to finally see the light of his world', 'taking weight off their shoulders', 'setting a golden path to justice and hope', 'opening people’s eyes to a new chapter of peace.', 'Life gave him many opportunities', 'yet he chose to walk a balance beam.', 'William Whipper was love.'] }
  ]
 },
 {
  id: 'fauset', name: 'Jessie Fauset', dates: '1882 – 1961', onNotables: true,
  students: 'By Brooke, Zoie, Ronald, Jabril, Jimir, Kevin, Fatima and Layla, grade 3',
  intro: `Jessie Fauset was like a midwife. She helped to birth the Harlem Renaissance. She encouraged a lot of writers. She worked for the Crisis Magazine as an editor, and she was co-editor for the Brownies Magazine, which was for African American children to learn about their culture.`,
  story: [
   `Jessie Fauset was like a midwife. She helped to birth the Harlem Renaissance. She encouraged a lot of writers. She worked for the Crisis Magazine as an editor, and she was co-editor for the Brownies Magazine, which was for African American children to learn about their culture.`,
   `Jessie Fauset was born in Camden County, New Jersey, on April 27, 1882. She moved to Philadelphia, Pennsylvania, and she went to Philadelphia High School for Girls. She was the only African American in her class. When she finished high school, she wanted to go to Bryn Mawr College, but the college wouldn’t accept African American students. Instead, they helped her get a scholarship at Cornell University in New York.`,
   `Jessie Fauset graduated from Cornell University in 1905. After she graduated she went to Washington, D.C. and taught French and Latin. Later she went to France and kept working on learning French at the Sorbonne. She got her Master’s degree in French at the University of Pennsylvania in 1919.`,
   `In the same year, W.E.B. Du Bois hired Jessie Fauset to be an editor at the Crisis Magazine, which was also called “A Record of the Darker Races”. The Crisis Magazine was started by W.E.B. Du Bois and it was for African American people so they could know their heritage. It had news, poetry, short stories and opinions. At the Crisis, Jessie Fauset supported new voices by putting their writing in the magazine. She also was the co-editor of the Brownie Magazine, which was for African American children. It had poems, stories about very important dark-skinned people, short stories, puzzles, beautiful illustrations and a column by W.E.B. Du Bois called “As the Crow Flies”.`,
   `Jessie Fauset left the Crisis in 1926, and she went to New York City to teach French. She wanted to be an editor, but they wouldn’t accept their first Black editor at big, New York publishing houses. So she wrote novels. The main novels were Plum Bun, The Chinaberry Tree and Comedy, American Style. Jessie got married to a businessman in 1929. After her husband died, she moved back to Philadelphia and lived with her half brother until she died in 1961.`
  ],
  letter: null,
  poems: [
   { title: 'Ode to Jessie Fauset', by: 'Jubilee School students', lines: ['You were like a book', 'writing your own legacy.', 'You were an owl full of knowledge.', 'You showed a new perspective of hope;', 'You shone the truth into our eyes.', 'You enlightened us with words of empowerment.', 'You were a huntress who hunted', 'for greatness.'] }
  ]
 },
 {
  id: 'waring', name: 'Laura Wheeler Waring', dates: '1887 – 1948', onNotables: true,
  students: 'Introduction by Khaseem — poem by Nyla',
  intro: `In 1887 an amazing person was born: Laura Wheeler Waring. Laura was an artist and her art was how she showed Black people’s history to the world. Black people were treated like they were invisible by white people for many years. Laura painted pictures of Black people so other people could see them and realize that African Americans should be respected. She helped to make it so Black people were appreciated. Laura Wheeler Waring was a big part of the Harlem Renaissance, which gave African Americans more freedom to be who they were.`,
  story: [],
  letter: null,
  poems: [
   { title: 'Laura’s Paintings', by: 'Nyla', lines: ['Laura’s paintings', 'on canvases made of clouds', 'paints made from the sun’s rays', 'shooting down from the sky', 'each stroke like waves of the ocean.', '', 'The skin of people in Laura’s paintings', 'shine in the night sky', 'removing the cloak of invisibility', 'showing the true worth', 'and strength', 'of African Americans'] }
  ]
 },
 {
  id: 'blockson', name: 'Dr. Charles L. Blockson', dates: '1933 – 2023', onNotables: true,
  students: 'By Miles, Joshua, Marabella, Noah, Minna, Emerson & Deyvon, grade 3; and Ke’yier, Zuri, Khaseem, Nyla & Journey, grade 4',
  intro: `Dr. Charles Blockson was a knowledge collector and he gave that knowledge to the world. He triumphed in proving the worth of his ancestors by collecting books and artifacts to show his Black history. Dr. Blockson wanted children in the future, like us, to know their Black history. Dr. Blockson was digging deep for knowledge and power for African Americans and Black people around the world. His spirit is still teaching the world.`,
  story: [
   `Dr. Charles Blockson was a knowledge collector and he gave that knowledge to the world. He triumphed in proving the worth of his ancestors by collecting books and artifacts to show his Black history. He loved to share his collection and knowledge wherever he went. Dr. Blockson wanted children in the future, like us, to know their Black history. He went through generations to study Black people’s experiences. We should all look up to him as a role model. He encouraged us to try harder to learn our history. His spirit is still teaching the world.`,
   `Dr. Blockson was born on December 16, 1933 in Norristown, Pennsylvania. He was the oldest of eight siblings. When Dr. Blockson was in class at the age of nine, his class was learning about white people’s history. He asked his white substitute teacher what about Black people? She said that “Negroes” don’t have a history; they were meant to serve white people. Charles was shocked. He told his parents what she said and they told him that Black people have an important history. It made him want to collect Black history and to prove how amazing Black people’s ancestors were.`,
   `When Dr. Blockson was ten he was sitting on a box in his backyard and his grandfather was talking to him about his family and the Underground Railroad. This is what he wrote about it: “I remember it as if it were yesterday the moment when the Underground Railroad in all its abiding mystery and hope and terror took possession of my imagination.”`,
   `This is a quote from Dr. Blockson’s grandfather: “‘My father — your great grandfather, James Blockson — was a slave over in Delaware and escaped to Canada’. Grandfather knew little more than these bare details about his father’s flight to freedom, for James Blockson… kept the secrets of the Underground Railroad locked in his heart until he died.” His great grandfather’s story inspired Dr. Blockson to collect Black history books to learn more about the Underground Railroad and teach others about it. He learned the secrets of the Underground Railroad.`,
   `When Dr. Blockson was in his college time at Penn State University he was a professional athlete in track and field and football. He was called “Blockbuster Blockson” because he was strong, brave and talented in football. Blockson was so good at sports that the New York Giants offered him a spot on their team. But Blockson was not into being rich or being in the NFL. He was focused on his Black history collection.`,
   `Blockson graduated from Penn State in 1956. After college he served in the US Army. While he served in the army he started to have a love for travel, and found bookstores with Black history information. In 1958 he got married to Elizabeth Parker and Charles and Elizabeth had a child named Noelle Parker Blockson.`,
   `Ever since he was a child, Dr. Blockson collected old records, newspapers, books and more. He was looking for anything that had the words Negro, Black or African. He wanted to collect Black history because of when his substitute teacher told him there was no history, and when his grandfather told him how his ancestors got freedom from slavery on the Underground Railroad. Stories about Black history really inspired him. He collected books and items because of the need to have people learn about Black history. Dr. Blockson brought some of his collection to Penn State because he graduated from there. His collection at Penn State is called the Charles L. Blockson Collection of African-Americana and the African Diaspora. Some places that he got his collection from are the Caribbean, Africa and Latin America. Some of his collection dates all the way back to 1632. Some of his first edition collections were from W.E.B. Du Bois, Phyllis Wheatly, Toussant L’Ouverture and Paul Robeson.`,
   `1984 is when the Charles L. Blockson Afro-American Collection Library opened at Temple University. An assistant from the President’s office at Temple had called the poet Professor Sonia Sanchez and asked what she knew about Dr. Blockson. Sonia Sanchez was surprised that he didn’t know about him so she introduced him and other people from Temple to Dr. Blockson and his collection. After Dr. Blockson met the people from Temple he officially donated his collection to Temple University. When he first donated his collection he had 150,000 items, but as of 2023 he had 700,000 artifacts and books. Some of his collection was from 1581. In 2016 Dr. Blockson donated thirty nine items from Harriet Tubman to the National Museum of African American History and Culture at the Smithsonian Institution.`,
   `Dr. Blockson collected relics and artifacts of African American history and he changed the world by spreading his knowledge of Black history and culture to our generation and to students around the world. He said “We’re preserving the history to pass on to our students”. He was inspiring because he taught us about the Underground Railroad and African American history that we would never have known. Dr. Molefi Kete Asante said “Blockson was a man who hunted in the forest of knowledge, and the books that he discovered became trophies that did not sit on shelves but instead actively energized an entire population.” Dr. Blockson was digging deep for knowledge and power for African Americans and Black people around the world.`
  ],
  letter: null,
  poems: [
   { title: 'Ode to Dr. Blockson', by: 'Jubilee School students', lines: ['You were a glorious collector', 'of the gold of knowledge.', 'You taught us to know our history.', 'You light up the day', 'and help Black people know who we are.', 'Your soul is teaching Black history.', 'You sprinkle our heads', 'with knowledge from above.', 'We are plants', 'and you are feeding us with water.', 'You are water', 'that we jump into for knowledge.', 'You are sparkling like a shooting star', 'revolving around the solar system', 'spreading knowledge to the world.'] }
  ]
 },
 {
  id: 'perry', name: 'Christopher J. Perry', dates: '1854 – 1921', onNotables: true,
  students: 'By Jubilee School students',
  intro: `Christopher Perry was a great writer ever since he was young. He started writing for newspapers when he was fourteen. About ten years later he decided to create his own newspaper, The Philadelphia Tribune. He started the Philadelphia Tribune to speak against racism and to protect his people. He said: “For my people to make progress they must have a newspaper through which they can speak against injustice”. Perry used the Philadelphia Tribune to tell the truth about what was happening around the world.`,
  story: [
   `Christopher J. Perry was born in Baltimore, Maryland on September 11, 1854. He went to school there even though the schools were segregated and not equipped with what they needed. He completely changed his life when he moved to Philadelphia. For starters, he got a better education. Christopher Perry was a great writer ever since he was young. He was credited with his writing skills even at a young age. He started writing for newspapers when he was fourteen.`,
   `At age twenty eight, Christopher Perry lost his job because the newspaper he worked for went bankrupt. He decided to create his own newspaper, The Philadelphia Tribune. He started the Philadelphia Tribune to speak against racism and to protect his people. He said: “For my people to make progress they must have a newspaper through which they can speak against injustice”. Perry used the Philadelphia Tribune to tell the truth about what was happening around the world. W.E.B. Du Bois said this about Perry: “The paper represents pluck and perseverance on the part of the publisher.”`,
   `In May, 1921 Christopher Perry died. The headline in the Tribune said: “The Sage of Race Journalism Quietly Passes into The Great Beyond”. When Perry died he was succeeded by Beatrice Perry, his daughter. Beatrice then made Grant Williams the editor. He died a year later and was succeeded by Eugene Rhodes.`
  ],
  letter: [`Dear Christopher Perry,`, `Thank you for the gift and the knowledge you gave us through exposing lies and telling the truth about injustice in your newspaper “The Philadelphia Tribune”. Thank you for spreading the word that Black people weren’t being treated fairly. You guided us into the land of truth. Your voice is like rain in the desert.`],
  poems: []
 },
 {
  id: 'jones', name: 'Absalom Jones', dates: '1746 – 1818', onNotables: true,
  students: 'By Anela, Connor, Nahla & Aasimah, grades 5 & 6 — Mary Thomas tribute by Ewuare',
  intro: `Absalom Jones is a crucial part of Philadelphia history. He was a leader, a preacher and an activist. He founded a society to help already free Black people and he appealed to the government to get them to outlaw slavery. He was one of the most important members of the early abolition movement. He was the first African American to be ordained by the Episcopal Church. Absalom Jones said he founded the church “to encourage us to arise out of the dust and shake ourselves, and throw off that servile fear, that the habit of oppression and bondage trained us in.”`,
  story: [],
  letter: [`Dear Absalom Jones,`, `Thank you for making it so we have a better life than we would have had without you, because you helped Black children get a better education. You showed bravery, courage and integrity in the face of segregationist laws and the hate that came with them. Thank you for saving lives and giving aid to Black widows and children. Thank you for expanding our knowledge of how religion can be used as a tool to help the oppressed by founding the African Church.`],
  poems: [
   { title: 'Mary Thomas — a tribute in her voice', by: 'Ewuare', note: 'Written for Mary Thomas, the wife of Absalom Jones. In performance the piece closes with a sung medley of “In a Sentimental Mood” and “For Once in My Life.”', lines: ['To the man who oppresses me', 'I am but a cow, an ox', 'To be worked and bred until I am dead', 'Though he believes he treats me good', 'I know when he looks at me', 'I am nothing more than currency… To be made', '', 'A line scribbled in his budget book', 'Valuable, yes', 'But only for my body’s value to him', '', 'I confess I never permitted myself', 'The luxury of ever believing I would be free one day', 'A slave has no time for such fantasies', 'The brutality of this life', 'Leaves just enough hope to make it through the day', '', 'And yet…', 'This man…', 'I call him that for that is WHO he is', 'The truest I know', 'Who loves me', 'Not for what I am but for WHO I am and KNOW myself to be', 'Who treats me with kindness first', 'And respect follows closely behind.', '', 'This man who says he wishes to wed ME.', 'But, before I can revel in the joy one would expect', 'My mind is a beehive of worry', 'For yes, my mistress would welcome this.', 'But not for reasons worthy of such bliss.', 'Her motives are monetary', 'As such a union would assure her an increase untold', 'But as much as I love this man', 'I LOATHE the notion of birthing my children into the waiting hands', 'of those who would sell them', 'just as soon as the cord was cut', '', 'And so, my nights have been restless', 'I seek dreams when only nightmares await me', 'In the homes I work', 'They talk unceasingly about liberty and justice for all', 'And yet I know that I am not included in their all', 'Just by the way they LOOK at me, SPEAK to me…', '', 'But… when I look at THIS man', 'I see my prayers answered', 'Not for freedom so much', 'As for companionship', 'A refuge for my work-wearied heart', 'Wed him I will', 'Whether slave or freed', 'For in this love we have found', 'a FREEDOM no one can take from us.'] }
  ]
 },
 {
  id: 'bustill', name: 'Cyrus Bustill', dates: '1732 – 1806', onNotables: false,
  students: 'By Connor, grade 6',
  intro: `Cyrus Bustill was one of the most influential figures in America’s history. He served his country valiantly. He helped found the Free African Society, which was a group dedicated to the enrichment of Black people’s lives. He made sure people got medicine when they required it. He helped widows and fatherless children. He helped appeal to Congress for the abolition of slavery. Cyrus Bustill was a hero.`,
  story: [
   `Cyrus Bustill was a leader, a feeder, and an abolitionist. He was involved in the Revolutionary War and helped found the Free African Society. He was the ancestor of many activists to come.`,
   `Cyrus Bustill was born February 2nd in 1732. He was born in Burlington, New Jersey. His parents were white Quaker lawyer Samuel Bustill and Parthenia, an African woman who was an enslaved woman owned by his father. He learned how to bake from Thomas Prior.`,
   `Bustill has done so many amazing things. He founded a school in his home for Black people. He founded Mercy-Douglass Hospital, a hospital that would take in Black people, and wasn’t segregated. He is also the ancestor of Sara Mapps-Douglass and Paul Robeson. In 1791 Bustill owned twelve acres in the Black settlement of Guineatown, which was huge for a Black person back then.`,
   `When he was around 59 Cyrus enlisted in the Military during the Revolutionary War. Instead of being a fighter standing on the front lines, he was a baker which was equally important because without him, the soldiers would have died of starvation.`,
   `Bustill also had a hand in abolitionist work. He helped found the Free African Society, which was a group dedicated to the enrichment of Black people’s lives. He made sure people got medicine when they required it. He helped widows and fatherless children. He helped appeal to Congress for the abolition of slavery.`,
   `In conclusion, Cyrus Bustill was one of the most influential figures in America’s history. He served his country valiantly. He freed the enslaved and oppressed. He founded a place of healing. Cyrus Bustill was a hero.`
  ],
  letter: [`Dear Cyrus Bustill,`, `You saved soldiers by baking for the military during the Revolutionary War. You founded a school for Black children to get a better education. You made a hospital for the Black community because Black people weren’t being treated fairly and slavery still existed. Black Americans were treated like nothing at all and you were like a lantern in the dark that showed light and hope. You flew high like your descendents Sara Mapps-Douglass and Paul Roberson. You’re like a gem that shines freedom. You inspire people like artwork does. You have a heart of gold and a soul of diamonds. You inspire us to be heroes just like you.`],
  poems: []
 },
 {
  id: 'douglass', name: 'Sarah Mapps Douglass', dates: '1806 – 1882', onNotables: false,
  students: 'By Jubilee School students',
  intro: `Sarah Mapps Douglass, a strong African American educator, abolitionist, writer and artist stands as a testament to the resilience and intellectual prowess of Black women in the 19th-century. Through her strong efforts in education, she not only provided invaluable opportunities for Black students but also laid the groundwork for future generations of educators and activists.`,
  story: [
   `Sarah Mapps Douglass, a strong African American educator, abolitionist, writer and artist, stands as a testament to the resilience and intellectual prowess of Black women in the 19th-century.`,
   `Sarah Mapps Douglass was born in 1806 in Philadelphia PA. She was the only child born into an abolitionist family and was the only daughter of Robert Douglas, a baker and her mother Grace Bustill, a milliner. Her mother was also an active abolitionist. Like many women in Sarah’s time she became a teacher while being an active abolitionist. Sarah followed her mother’s steps and joined her mother as a founding member of the bi-racial Female Anti-Slavery society in 1833.`,
   `Sarah kept up with her education while being a teacher. She joined classes on anatomy, physiology and hygiene in 1850. Sarah Mapps Douglass was the first Black woman to attend the Female Medical College of Pennsylvania. While at the college she gained a reputation for women’s hygiene and health. Sarah Mapps Douglass attended college, and then taught briefly in New York City. In 1825, she began teaching in Philadelphia at a school organized by her mother with James Forten. Starting in 1833, she taught briefly at the Free African School for Girls. Douglass regularly traveled to New York to give academic lectures and also left behind a considerable number of written works. She wrote articles for various newspapers.`,
   `Sarah Mapps Douglass’s legacy as an educator, abolitionist, and writer is a powerful testament to her unwavering commitment to social justice and the empowerment of African Americans. Through her strong efforts in education, she not only provided invaluable opportunities for Black students but also laid the groundwork for future generations of educators and activists.`
  ],
  letter: [`Dear Sarah Mapps Douglass,`, `You were an intelligent and strong woman. You worked hand and foot to gain your place in society. You had potential since you were born. You were a multi-tasker; you accomplished many things at once. As a teacher you gave lectures; important lectures helping the Black community. And that led to you becoming a founding member of the Bi-racial Female Anti-slavery Society. You also taught at a school organized by your mother and James Forten. You continued to do amazing things until your passing.`],
  poems: []
 },
 {
  id: 'dickerson', name: 'G. Edward & Addie Dickerson', dates: '', onNotables: false,
  students: 'By La’Ani, Madison, Rayvon, Nati and Jazmyn, grade 5; Zorai, Sekou, Zoie, Akoni and Reanna, grade 6',
  intro: `Edward and Addie Dickerson were a determined and hardworking couple who fought to better the lives of Black people. They were fighting against oppression in South Philadelphia and around the world. They were very close, and got a lot of ideas from each other to help their Black community. Their partnership would never be broken.`,
  story: [
   `Edward and Addie Dickerson were a determined and hardworking couple who fought to better the lives of Black people. They were fighting against oppression in South Philadelphia and around the world. They were very close, and got a lot of ideas from each other to help their Black community. Their partnership would never be broken.`,
   `Edward Dickerson brought equality and freedom to Philadelphia by defending our people. He was the man willing to sacrifice his life for our rights. He was a trustworthy person. Edward made his people feel like there was still hope.`,
   `Edward Dickerson was born in 1873 in Virginia. He spent most of his childhood on a tobacco farm. He had dirt floors in his house, and was a penniless boy. He walked five miles everyday to school. In the late 1800’s, Edward moved to Philadelphia and went to Temple University Law School. While he was in Temple he shined boots to make money. He graduated from the law school in 1902. Edward was the first Black person to graduate from Temple Law School.`,
   `In the summer of 1918, Edward defended many Black people who were in the riots in South Philadelphia. Adela Bond, a Black probation officer, wanted to buy a house in South Philadelphia. The real estate agent who sold houses in South Philly said that “the colored tenants are far better tenants than the elements we have now”. The house that Adela bought was in an all-white neighborhood. After she moved in, a mob of white men surrounded her house. One of the people in the crowd threw a rock at her window. Since she was a probation officer, she had a gun. Adela shot into the mob of white men and injured a man named Kelly. Then she called the police. The riots and the police coming together started chaos.`,
   `After the riots, Edward sued the county of Philadelphia for the damages. He prosecuted a white police officer for beating up a Black man, Preston Lewis, in his hospital bed. The white officer had brutalized Preston Lewis, an innocent Black man who was trying to escape from the riots. At the time it was very rare for a white police officer to get prosecuted for abusing a Black citizen. Edward defended Black people from the riots and got them off, including Adela Bond. “Can you blame citizens of color for mobilizing… to protect one of their own?” wrote Grant Williams, the Tribune editor.`,
   `Edward Dickerson ran for judge in 1923 and in 1932. He took a case before the Supreme Court; at that time it was very unusual for a Black man to do that. It took a strong Black man to defend another Black man in front of the Supreme Court. He was the City Solicitor, and he also defended people throughout the South Philadelphia footprint who had difficulty finding housing in the area. Addie also helped with housing because she was a real estate broker.`,
   `Addie Dickerson, Edward’s wife, was an inspiring woman to people of color and women. She worked hard to obtain rights for Black people everywhere. As a real estate broker, she signed many deeds for people to own properties. As well as being a real estate broker, she became the first Black notary public. She was also a part of prominent international associations and organizations.`,
   `One of the main groups that Addie was a part of was the International Council of Women of the Darker Races. The ICWDR’s focus was to spread information around the world about Black people’s history. Booker T. Washington’s wife, Margaret Murray Washington, founded the ICWDR in 1922. The ICWDR started study clubs in Haiti and Cuba. They also pursued an education program in Liberia.`,
   `In 1927, Addie Dickerson represented the ICWDR in the Pan African Conference. The Pan African Movement and the ICWDR both shared information about Black achievements, and history about the darker races. They wanted to bring people of African descent together. Addie Dickerson was also part of the Women’s International League for Peace and Freedom. Many members of the NAACP were members of the WILPF, which W.E.B. Du Bois and his wife Nina Du Bois supported. This group, like the ICWDR, was for peace and women’s rights. The group held a conference in Prague, Czechoslovakia, in 1924. At the conference, Addie was one of two women of color who were delegates. Seventy six countries were represented, and one hundred and seventy one delegates attended the conference.`,
   `Addie Dickerson carried women and Blacks through difficult times. She supported women of color, and peace. Addie became well known for her work in the ICWDR. She was even invited to a conference at the White House that Herbert Hoover called about Black people in the United States.`,
   `Addie and Edward Dickerson were a powerful couple who fought for Black people’s and women’s rights, and for peace. Addie and Edward cooperated through working together. They worked as equal partners to change the world.`
  ],
  letter: [`Dear Addie and Edward,`, `You were some of the leaders that brought freedom to our people. Thank you for doing so much for us. Edward and Addie you are inspiring. We will make sure people honor you.`, `Edward, it’s really important how you sued the City of Philadelphia for the damages from the riot of whites outside a person of color’s house. You were the first Black man to get a white police officer prosecuted for abusing a person of color. Edward, you were very brave to stick up for your people in the courtroom. You defended a lot of Black people. Thank you for sacrificing your life for your people.`, `Addie, you were an amazing person. You fought for our rights. You were trying to get world peace. Thank you, Addie, for helping children of color around the world to learn their own history and to dive deeper into their history. You were trying to make the world safer and more peaceful for people of color. The things you did inspire us to try to be leaders.`, `Edward and Addie, your relationship made history because your partnership was so strong it couldn’t be broken. We feel like royalty because you are our family and our kings and queens.`],
  poems: [
   { title: 'The Epic Roots of the Dickersons', by: 'Morgan, Euree, Yasir, Connor, Felix, Priscilla, Joshua, Nomi and Anela, 4th grade', lines: ['A gift to the world', 'Warm like spirits in history', 'Overgrown in the walls of history', 'Marcus Garvey', 'Mary McCleod Bethune', 'William Monroe Trotter', 'Edward and Addie Dickerson.', '', 'Carrying history on our backs', 'Flying over history on a bird’s back', 'A series of tunnels running through history', 'Informing us of our past', 'As the past reveals the future.', '', 'Recognizing the gaping hole in justice', 'Part of the tree of equality', 'The Dickersons’ history wraps around the world', 'Like vines wrap around a tree', 'Heartful like the roots of a tree', 'Their legacy still in our veins today.'] }
  ]
 },
 {
  id: 'smith', name: 'Harriet Smith', dates: '1853 – 1946', onNotables: false,
  students: 'By Jubilee School students',
  intro: `Harriet Smith was born close to the end of slavery in America. We are very lucky that she happened to still be alive until 1946. John Henry Faulk managed to interview her in 1941. Because of this, her voice is forever preserved. She can teach us so much about slavery, even from beyond the grave.`,
  story: [
   `Harriet Smith was born close to the end of slavery in America. We are very lucky that she happened to still be alive until 1946. John Henry Faulk managed to interview her in 1941. Because of this, her voice is forever preserved. She can teach us so much about slavery, even from beyond the grave. We are very fortunate for her to have shared her story with us.`,
   `When Harriet was 6½ years old, the news of the Emancipation Proclamation came to the plantation she was enslaved on. She was born and enslaved in Hempstead, Texas in the June of 1853 on the Tuckahoe Plantation. Her master was Jim Bunton, or as Harriet called him, “J. B the Baby Boy.” Harriet was one of the lucky slaves. She didn’t even understand she was enslaved until she was six years old. Her master also owned her mom who was the cook, and her grandmother who ploughed oxen, a task Harriet did as well. She had two siblings, who were also born enslaved, a brother named George, and a sister named Ida. All the others were born free. We don’t know their names. She stayed on the plantation and rented it out. Afterwards, her dad bought a home across from the creek. He stayed there while Harriet stayed on the plantation but stayed with her Aunt Rose and Uncle George from time to time. Shortly after her dad left she got married at a young age, according to her “I don’t know, about seventeen, eighteen years old. Well, maybe not that old. I didn’t know my age. But ma and them knew. They didn’t tell us, though. We just guessed at it.” This is because it was common for enslaved people to not know their age.`,
   `After a while, Harriet Smith’s husband, J.S., was murdered. He was killed by not just anybody, but a man Harriet raised from birth. He was killed over politics.`,
   `Harriet Smith had an interesting life from start to finish, and we got to hear about it in her words. This is a fantastic opportunity to learn what it was like right after slavery times. We are extremely lucky to have had the opportunity to hear her voice.`
  ],
  letter: null,
  poems: []
 }
];
