export const NOTABLES = [
 {
  "name": "Julian Frances Abele",
  "hon": "",
  "dates": "1881–1950",
  "type": "Architecture",
  "section": "Martin J. Lehmann",
  "lot": "178",
  "bio": "Architect: Free Library of Philadelphia, Philadelphia Museum of Art, Duke University",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Julian_Abele",
  "img": "https://upload.wikimedia.org/wikipedia/commons/8/89/Julian_Abele%2C_photograph.jpg"
 },
 {
  "name": "Howard Hamilton Mackey",
  "hon": "",
  "dates": "1901–1987",
  "type": "Architecture",
  "section": "Lebanon",
  "lot": "938",
  "bio": "Architect, artist; founder and dean, Howard University School of Architecture and City Planning",
  "mil": "",
  "link": "https://www.philadelphiabuildings.org/pab/app/ar_display.cfm/23563",
  "img": ""
 },
 {
  "name": "David Bustill Bowser",
  "hon": "",
  "dates": "1920–1900",
  "type": "Art",
  "section": "Lebanon",
  "lot": "23",
  "bio": "Artist, painter, portraitist; designer of U.S.C.T. regimental flags, One of the first Black women doctors in Pennsylvania/ICY grad/Daugther to William Still",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/David_Bustill_Bowser",
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/4a/David_Bustill_Bowser.png"
 },
 {
  "name": "Frances Ellen Watkins Harper",
  "hon": "",
  "dates": "1825–1911",
  "type": "Art",
  "section": "John Brown",
  "lot": "487",
  "bio": "Abolitionist, author, and poet known as \"The Bronze Muse\"; wrote \"Bury Me in a Free Land\"",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Frances_Ellen_Watkins_Harper",
  "img": "https://upload.wikimedia.org/wikipedia/commons/8/88/Women_of_distinction_-_remarkable_in_works_and_invincible_in_character_%281893%29_%2814598047448%29.jpg"
 },
 {
  "name": "Gertrude B. Mossell",
  "hon": "",
  "dates": "d. 1928",
  "type": "Art",
  "section": "Lebanon",
  "lot": "661",
  "bio": "Mother of Sadie Turner Mosell Alexaner",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Gertrude_Bustill_Mossell",
  "img": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Gertrude_E.H._Bustill_Mossell%2C_c1890_%28cropped%29.jpg"
 },
 {
  "name": "Laura Wheeler Waring",
  "hon": "",
  "dates": "1887–1984",
  "type": "Art",
  "section": "Lebanon",
  "lot": "680",
  "bio": "Artist, educator, illustrator; founded art and music programs at Cheyney University",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Laura_Wheeler_Waring",
  "img": "https://upload.wikimedia.org/wikipedia/en/c/c1/Photo_of_Laura_Wheeler_Waring.jpg"
 },
 {
  "name": "Edward Cooper Brown",
  "hon": "",
  "dates": "1877–1928",
  "type": "Business",
  "section": "Celestine",
  "lot": "805",
  "bio": "Bank owner, financier, real estate developer",
  "mil": "",
  "link": "https://old.lva.virginia.gov/public/dvb/bio.asp?b=Brown_Edward_C.",
  "img": ""
 },
 {
  "name": "Henrietta S. Bowers Duterte",
  "hon": "",
  "dates": "1817–1903",
  "type": "Business",
  "section": "Lebanon",
  "lot": "128",
  "bio": "Business person, milliner; early female undertaker; assisted in the Underground Railroad",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Henrietta_Duterte",
  "img": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Henrietta_Duterte.jpg"
 },
 {
  "name": "James Forten",
  "hon": "",
  "dates": "1766–1842",
  "type": "Business",
  "section": "Lebanon",
  "lot": "25",
  "bio": "Abolitionist, businessman, philanthropist",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/James_Forten",
  "img": "https://upload.wikimedia.org/wikipedia/commons/9/94/James_Forten_%28cropped%29.jpg"
 },
 {
  "name": "Col. John McKee",
  "hon": "",
  "dates": "1821–1902",
  "type": "Business",
  "section": "Celestine",
  "lot": "1024",
  "bio": "Millionaire, real estate tycoon",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/John_McKee_(philanthropist)",
  "img": "https://upload.wikimedia.org/wikipedia/en/4/49/Colonel_John_McKee.png"
 },
 {
  "name": "Church of the Crucifixion",
  "hon": "",
  "dates": "d. ",
  "type": "Church",
  "section": "Lebanon",
  "lot": "712 - 715",
  "bio": "Lot range 712-715",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Church of the Annunciation of the Blessed Virgin Mary",
  "hon": "",
  "dates": "d. ",
  "type": "Church",
  "section": "Olive",
  "lot": "443",
  "bio": "Also lot(s): 444, 448, 495",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "John Pierre Burr",
  "hon": "",
  "dates": "1792–1864",
  "type": "Civil Rights",
  "section": "Olive",
  "lot": "72",
  "bio": "Abolitionist; founder of the Demosthenian Institute; organizer, PA Anti-Slavery Society; promoted emigration to Haiti",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/John_Pierre_Burr",
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/14/John_Pierre_Burr.jpg"
 },
 {
  "name": "Octavius Valentine Catto",
  "hon": "",
  "dates": "1839–1871",
  "type": "Civil Rights",
  "section": "Lebanon",
  "lot": "124",
  "bio": "A prominent 19th-century educator, civil rights pioneer, and baseball leader in Philadelphia",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Octavius_Catto",
  "img": "https://upload.wikimedia.org/wikipedia/commons/d/db/Octavius_Catto.jpg"
 },
 {
  "name": "William Whipper",
  "hon": "",
  "dates": "1804–1876",
  "type": "Civil Rights",
  "section": "Olive",
  "lot": "353",
  "bio": "Abolitionist, entrepreneur, philanthropist; co-founder, American Moral Reform Society",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/William_Whipper",
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/45/William_Whipper.png"
 },
 {
  "name": "James F. Needham",
  "hon": "",
  "dates": "1848–1936",
  "type": "Civil Sector",
  "section": "Lebanon",
  "lot": "589",
  "bio": "Oddfellows leader - Helped build the first Black Office Buildling. ICY Grad. Civil Sector Leader",
  "mil": "",
  "link": "https://www.1838blackmetropolis.com/post/needham",
  "img": "https://static.wixstatic.com/media/af048d_600c803a495f4f88a92166f0861caf24~mv2.png/v1/fill/w_774,h_1762,al_c,q_90/af048d_600c803a495f4f88a92166f0861caf24~mv2.webp"
 },
 {
  "name": "Matthew Anderson",
  "hon": "Rev.",
  "dates": "1848–1928",
  "type": "Clergy",
  "section": "Celestine",
  "lot": "997",
  "bio": "Founder of Berean Presbyterian Church, the Berean Institute, and Berean Savings and Loan",
  "mil": "",
  "link": "https://pcusa.org/news-storytelling/blogs/historical-society-blog/whole-gospel-whole-community-legacy-matthew-anderson",
  "img": "https://pcusa.org/sites/default/files/styles/responsive_1400w/public/migrate/images/smallerborder16-0022_01.jpg.webp?itok=L5E3kIKI"
 },
 {
  "name": "Bishop George L Blackwell",
  "hon": "",
  "dates": "1862–1926",
  "type": "Clergy",
  "section": "John Brown",
  "lot": "38",
  "bio": "Author; bishop of the A.M.E. Zion Church",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/George_Lincoln_Blackwell",
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/52/George_Lincoln_Blackwell.jpg"
 },
 {
  "name": "Bishop Sherrod C. Johnson",
  "hon": "",
  "dates": "1901–1961",
  "type": "Clergy",
  "section": "Lebanon",
  "lot": "546",
  "bio": "Founder, Church of the Lord Jesus Christ of the Apostolic Faith",
  "mil": "",
  "link": "https://www.tcljc.com/bscj_bio.htm",
  "img": ""
 },
 {
  "name": "Absalom Jones",
  "hon": "Rev.",
  "dates": "1746–1818",
  "type": "Clergy",
  "section": "Lebanon",
  "lot": "39",
  "bio": "(cenotaph) A founder of the Free African Society and the African Episcopal Church of St. Thomas; First Grand Master, Prince Hall Grand Lodge F&AM of PA",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Absalom_Jones",
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Absalom-Jones_Peale.jpg"
 },
 {
  "name": "John Bunyan Reeve",
  "hon": "Rev.",
  "dates": "1831–1916",
  "type": "Clergy",
  "section": "Lebanon",
  "lot": "775",
  "bio": "Pastor, Lombard Street Central Presbyterian Church; organized the theological school of Howard University",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/John_Bunyan_Reeve",
  "img": "https://upload.wikimedia.org/wikipedia/commons/6/62/Rev._J._B._Reeve.jpg"
 },
 {
  "name": "Bishop Ida B. Robinson",
  "hon": "",
  "dates": "1891–1946",
  "type": "Clergy",
  "section": "David Bustill Bowser",
  "lot": "1136",
  "bio": "Founder, Mt. Sinai Holy Church of America Inc.",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Ida_B._Robinson",
  "img": ""
 },
 {
  "name": "Bishop Richard R. Wright",
  "hon": "",
  "dates": "1878–1967",
  "type": "Clergy",
  "section": "John C. Bowers",
  "lot": "195",
  "bio": "Sociologist; president of Wilberforce University; bishop, AME Church; first African American PhD from the University of Pennsylvania",
  "mil": "",
  "link": "https://blackpast.org/african-american-history/richard-robert-wright-jr-1878-1967/",
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Richard_Robert_Wright%2C_Jr.jpg"
 },
 {
  "name": "Pauline R. Oberdorfer Minor",
  "hon": "",
  "dates": "1889–1963",
  "type": "Divine Nine Founder",
  "section": "Martin J. Lehmann",
  "lot": "475",
  "bio": "Mezzo-soprano, composer, educator; a founder of Delta Sigma Theta Sorority, Inc.",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Pauline_Oberdorfer_Minor",
  "img": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Pauline_Oberdorfer_Minor.jpg"
 },
 {
  "name": "Arizona Cleaver Stemons",
  "hon": "",
  "dates": "1898–1980",
  "type": "Divine Nine Founder",
  "section": "Richard Allen",
  "lot": "11",
  "bio": "Social worker; a founder of Zeta Phi Beta Sorority",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Arizona_Cleaver_Stemons",
  "img": ""
 },
 {
  "name": "Nellie Rathbone Bright",
  "hon": "",
  "dates": "1899–1977",
  "type": "Education",
  "section": "Celestine",
  "lot": "311",
  "bio": "Educator, Poet and Author",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Nellie_Rathbone_Bright",
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/39/Nellie_Rathbone_Bright_in_1923.jpg"
 },
 {
  "name": "Caroline LeCount",
  "hon": "",
  "dates": "1846–1923",
  "type": "Education",
  "section": "Lebanon",
  "lot": "187",
  "bio": "Educator, orator, social activist",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Caroline_LeCount",
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Caroline_LeCount.jpg"
 },
 {
  "name": "John Trusty Gibson",
  "hon": "",
  "dates": "1878–1937",
  "type": "Entertainment",
  "section": "Celestine",
  "lot": "575",
  "bio": "Pioneer in developing theatrical entertainment",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/John_T._Gibson",
  "img": "https://upload.wikimedia.org/wikipedia/commons/f/f4/John_T._Gibson_Standard_Theatre_Philadelphia_PA_%281919%29.jpg"
 },
 {
  "name": "Cassey Family",
  "hon": "",
  "dates": "d. ",
  "type": "Family",
  "section": "Lebanon",
  "lot": "492",
  "bio": "Also listed: (Lebanon Cemetery) (Merion Memorial Park); right edge of location text cut off in scan",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Joseph_Cassey",
  "img": ""
 },
 {
  "name": "Bascom Family",
  "hon": "",
  "dates": "d. ",
  "type": "Family",
  "section": "Lebanon",
  "lot": "335",
  "bio": "Also buried elsewhere: (Lebanon Cemetery) (Merion Memorial Park)",
  "mil": "",
  "link": "https://www.facebook.com/philafund/posts/on-this-final-day-of-black-history-month-our-philafact-remembers-warley-bascom-s/2282823428627460/",
  "img": "https://scontent-lga3-2.xx.fbcdn.net/v/t1.6435-9/52355797_2282823405294129_4370034498176286720_n.jpg?stp=dst-jpg_tt6&cstp=mx970x725&ctp=s970x725&_nc_cat=107&ccb=1-7&_nc_sid=127cfc&_nc_ohc=zY65Wm-scswQ7kNvwHaqcON&_nc_oc=AdphMP8bj-2jA6o5plDP-AUa5zCabzFFInKcL4lCWOHEAU-JY0k6rSj6Pn7WWcBG1cA&_nc_zt=23&_nc_ht=scontent-lga3-2.xx&_nc_gid=A4d_5J6cQPZOgrqNUHrMEA&_nc_ss=7b289&oh=00_AQHn9-GQ3jXbWGDt6IpxUXMANtLInptu-Nyq6ro9_P6bmQ&oe=6A95897C"
 },
 {
  "name": "Bowers Family",
  "hon": "",
  "dates": "d. ",
  "type": "Family",
  "section": "Lebanon",
  "lot": "185",
  "bio": "Also lot(s): 186. Also buried elsewhere: (Lebanon Cemetery)",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Venning Family",
  "hon": "",
  "dates": "d. ",
  "type": "Family",
  "section": "Lebanon",
  "lot": "21",
  "bio": "Associated surnames: Codgell, Sanders, Stevens. Also lot(s): 22, 58, 59; (Lebanon)",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Mount Olive Lodge",
  "hon": "",
  "dates": "d. ",
  "type": "Fraternal",
  "section": "Lebanon",
  "lot": "319",
  "bio": "Also lot(s): 320",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Charles L. Blockson",
  "hon": "",
  "dates": "1933–2023",
  "type": "Historian",
  "section": "Lebanon",
  "lot": "20",
  "bio": "American historian, author, bibliophile and collector of books, historical documents, art and other materials related to the history and culture of African Americans",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Charles_L._Blockson",
  "img": "https://upload.wikimedia.org/wikipedia/commons/1/10/Charles_L._Blockson_in_home_office_%281971%29.jpg"
 },
 {
  "name": "William Carl Bolivar",
  "hon": "",
  "dates": "1847–1914",
  "type": "Historian",
  "section": "Lebanon",
  "lot": "404",
  "bio": "Bibliophile, journalist; \"The Pencil Pusher\"",
  "mil": "",
  "link": "https://epublications.marquette.edu/cgi/viewcontent.cgi?article=1011&context=provost_leadership",
  "img": ""
 },
 {
  "name": "William Henry Dorsey",
  "hon": "",
  "dates": "1837–1923",
  "type": "Historian",
  "section": "John C. Bowers",
  "lot": "393",
  "bio": "Artist, bibliophile, public historian",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/William_Henry_Dorsey",
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/b6/William_Henry_Dorsey.jpg"
 },
 {
  "name": "Leon Gardiner",
  "hon": "",
  "dates": "1890–1945",
  "type": "Historian",
  "section": "Celestine",
  "lot": "250",
  "bio": "Last member of the American Negro Historical Society. Donated the collection to the Historical Society of Pennsylvania. This collection includes the Jacob C. White Sr. papers, and the founding documents of Lebanon Cemetary.",
  "mil": "",
  "link": "https://drive.google.com/drive/u/0/search?q=leon%20gardiner",
  "img": ""
 },
 {
  "name": "Celestine Cromwell",
  "hon": "",
  "dates": "1854–1902",
  "type": "History",
  "section": "Celestine",
  "lot": "138",
  "bio": "First burial at Eden Cemetery",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "William Dressen",
  "hon": "",
  "dates": "1882–1921",
  "type": "History",
  "section": "Richard Allen",
  "lot": "489",
  "bio": "\"Alabama Joe\" — one of the infamous brought to justice by Richard \"Dick\" Anderson, Citizen of Eden",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Reginald A. Bryant",
  "hon": "",
  "dates": "1949–2010",
  "type": "Journalism",
  "section": "Celestine",
  "lot": "72",
  "bio": "A founder of the National Association of Black Journalists",
  "mil": "",
  "link": "https://www.phillytrib.com/news/tombstone-dedication-for-nabj-founder-bryant/article_bc34105b-45dc-5b5e-a721-faff3ce707c9.html",
  "img": ""
 },
 {
  "name": "T. Thomas Fortune",
  "hon": "",
  "dates": "1856–1928",
  "type": "Journalism",
  "section": "Olive",
  "lot": "428",
  "bio": "Editor, equal-rights leader, journalist, orator, writer; a founder of the National Afro-American League",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Timothy_Thomas_Fortune",
  "img": "https://upload.wikimedia.org/wikipedia/commons/9/97/T._Thomas_Fortune.jpg"
 },
 {
  "name": "Christopher J. Perry",
  "hon": "",
  "dates": "1854–1921",
  "type": "Journalism",
  "section": "Celestine",
  "lot": "1097",
  "bio": "Businessman; founder of the oldest continuously operated African American newspaper (Philadelphia Tribune)",
  "mil": "",
  "link": "https://www.phillytrib.com/site/about.html",
  "img": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Christopher_J._Perry.png"
 },
 {
  "name": "Arthur Huff Fauset",
  "hon": "",
  "dates": "1899–1983",
  "type": "Literature",
  "section": "Olive",
  "lot": "131",
  "bio": "Wrote Black Gods of the Metropolis.",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Arthur_Fauset",
  "img": "https://i0.wp.com/notablefolkloristsofcolor.org/wp-content/uploads/2022/10/Fauset.jpg?w=768&ssl=1"
 },
 {
  "name": "Jessie Redmon Fauset",
  "hon": "",
  "dates": "1882–1961",
  "type": "Literature",
  "section": "Olive",
  "lot": "93",
  "bio": "Editor, educator, essayist, poet, novelist; \"Godmother of the Harlem Renaissance\" (married name Harris)",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Jessie_R._Fauset",
  "img": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Negro_Poets_and_Their_Poems-0182.jpg"
 },
 {
  "name": "Robert Jones Abele",
  "hon": "Dr.",
  "dates": "1875–1929",
  "type": "Medicine",
  "section": "Celestine",
  "lot": "517",
  "bio": "A founder of Sigma Pi Phi Fraternity; first African American graduate of Hahnemann Medical School",
  "mil": "",
  "link": "https://blackpast.org/african-american-history/robert-jones-abele-1875-1929/",
  "img": "https://blackpast.org/wp-content/uploads/003_c278AbeleRobert-1280x1812.jpg"
 },
 {
  "name": "Caroline Still Wiley Anderson",
  "hon": "Dr.",
  "dates": "1848–1919",
  "type": "Medicine",
  "section": "Lebanon",
  "lot": "16",
  "bio": "Educator, physician, social activist",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Caroline_Still_Anderson",
  "img": "https://upload.wikimedia.org/wikipedia/commons/4/45/Caroline_Still_Anderson_circa_1890_%28cropped%29.jpg"
 },
 {
  "name": "Joseph Brister",
  "hon": "Dr.",
  "dates": "1840–1903",
  "type": "Medicine",
  "section": "Olive",
  "lot": "384",
  "bio": "He practiced dentristry. Had a cliinc on Pine with Dr. Bias. His son James was the First Black Dentist at Penn. Also buried elsewhere: (Olive Cemetery)",
  "mil": "",
  "link": "https://archives.upenn.edu/exhibits/penn-people/biography/james-brister/",
  "img": ""
 },
 {
  "name": "Rebecca J. Cole",
  "hon": "Dr.",
  "dates": "1846–1922",
  "type": "Medicine",
  "section": "Celestine",
  "lot": "476",
  "bio": "Physician, social reformer; second African American woman to earn an M.D.",
  "mil": "",
  "link": "https://blackpast.org/african-american-history/cole-rebecca-j-1846-1922/",
  "img": "https://blackpast.org/wp-content/uploads/2024/08/cole_rebecca.jpg"
 },
 {
  "name": "Edwin Clarence Howard",
  "hon": "Dr.",
  "dates": "1846–1912",
  "type": "Medicine",
  "section": "Lebanon",
  "lot": "24",
  "bio": "A founder of Sigma Pi Phi Fraternity and of St. Albans Lodge No. 35; first African American graduate of Harvard Medical School",
  "mil": "",
  "link": "https://blackpast.org/african-american-history/edwin-clarence-joseph-turpin-howard-1846-1912/",
  "img": "https://upload.wikimedia.org/wikipedia/commons/6/60/Edwin_Clarence_Howard_%281846%E2%80%931912%29.png"
 },
 {
  "name": "Walter Fitzgerald Jerrick",
  "hon": "Dr.",
  "dates": "1894–1953",
  "type": "Medicine",
  "section": "Celestine",
  "lot": "810",
  "bio": "A founder of The Pyramid Club; physician",
  "mil": "",
  "link": "https://blackpast.org/african-american-history/jerrick-walter-fitzgerald-m-d-1894-1953/",
  "img": ""
 },
 {
  "name": "Nathan Francis Mossell",
  "hon": "Dr.",
  "dates": "1856–1946",
  "type": "Medicine",
  "section": "Lebanon",
  "lot": "661",
  "bio": "Physician, social activist; founder of Douglass Memorial Hospital; first African American graduate of the University of Pennsylvania Medical School",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Nathan_Francis_Mossell",
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Nathan_Francis_Mossell_%281856-1946%29%2C_M.D._1882%2C_portrait_photograph_by_H.D._Carns_%26_Co%3B_Image_ID_27593990.jpg"
 },
 {
  "name": "Jeremiah Asher",
  "hon": "Rev.",
  "dates": "1812–7/27/1865",
  "type": "Military",
  "section": "Lebanon",
  "lot": "19",
  "bio": "Chaplain, ome fo the three Jeramiah's at Shiloh, Good friend of Elizabeth Taylor Greenfield",
  "mil": "Civil War · Chaplain · 6th Regt US Col'd Inf",
  "link": "https://en.wikipedia.org/wiki/Jeremiah_Asher",
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Jeremiah_Asher.jpg"
 },
 {
  "name": "Robert Penn",
  "hon": "",
  "dates": "1872–1912",
  "type": "Military",
  "section": "Harriet Tubman",
  "lot": "155",
  "bio": "Medal of Honor recipient, Spanish-American War",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Robert_Penn_(Medal_of_Honor)",
  "img": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Robert_Penn_%28MOH%29_framed.jpg"
 },
 {
  "name": "George Anderson",
  "hon": "",
  "dates": "1852–12/21/1909",
  "type": "Music",
  "section": "Harriet Tubman",
  "lot": "130",
  "bio": "musician; Camp William Penn",
  "mil": "Civil War · Musician · Co. I 32nd Regt US Col'd",
  "link": "",
  "img": ""
 },
 {
  "name": "Marian Anderson",
  "hon": "",
  "dates": "1897–1993",
  "type": "Music",
  "section": "Celestine",
  "lot": "1158",
  "bio": "Opera Singer, Social Reformer. A classical music pioneer and Opera Singer, she was a contralto known for her wide-ranging repertory of art songs, opera arias, and spirituals. She was one of the most celebrated singers of the twentieth century.",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Marian_Anderson",
  "img": ""
 },
 {
  "name": "James Hemmingway",
  "hon": "",
  "dates": "1800–1849",
  "type": "Music",
  "section": "Lebanon",
  "lot": "586",
  "bio": "Member of Frank Johnson's Band",
  "mil": "",
  "link": "https://www.1838blackmetropolis.com/post/a-fresh-look-at-francis-johnson-philadelphia-s-musical-magnet",
  "img": ""
 },
 {
  "name": "Henry Mobley",
  "hon": "",
  "dates": "1930–1986",
  "type": "Music",
  "section": "Celestine Reserve 2",
  "lot": "221",
  "bio": "\"Hank\" Mobley — jazz tenor saxophonist and composer",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Hank_Mobley",
  "img": "https://upload.wikimedia.org/wikipedia/en/0/08/Hank_Mobley.jpg"
 },
 {
  "name": "Charles Tindley",
  "hon": "Rev.",
  "dates": "1851–1933",
  "type": "Music",
  "section": "Celestine",
  "lot": "717",
  "bio": "Composer/songwriter of gospel hymns; leader during the Great Migration; \"Prince of Preachers\"",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Charles_Albert_Tindley",
  "img": "https://miro.medium.com/v2/resize:fit:4800/format:webp/1*XdKjuvoEAAKYs88ZVaD6-A.jpeg"
 },
 {
  "name": "Hon. George Henry White",
  "hon": "",
  "dates": "1852–1918",
  "type": "Politics",
  "section": "Celestine",
  "lot": "378",
  "bio": "Banker, educator, lawyer, U.S. Congressman",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/George_Henry_White",
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/39/Hon._G.H._White_Trim.jpg"
 },
 {
  "name": "Elizabeth Montier",
  "hon": "",
  "dates": "d. 1906",
  "type": "Revolutionary Era",
  "section": "Lebanon",
  "lot": "105",
  "bio": "Paul Robeson Ancestor. We have portraits",
  "mil": "",
  "link": "https://www.philamuseum.org/exhibitions/the-montiers-of-philadelphia",
  "img": "https://assets.philamuseum.org/images/r7hgx2l2/production/6be476d8e38b5f310442f2c9b577cca7379b07d7-438x550.jpg?w=1024&fit=max&auto=format"
 },
 {
  "name": "Hiram Charles Montier",
  "hon": "",
  "dates": "d. 1905",
  "type": "Revolutionary Era",
  "section": "Lebanon",
  "lot": "105",
  "bio": "Paul Robeson Ancestor",
  "mil": "",
  "link": "https://www.philamuseum.org/exhibitions/the-montiers-of-philadelphia",
  "img": "https://assets.philamuseum.org/images/r7hgx2l2/production/63267df519fcda89e7522065cca2749e2cb3d689-438x550.jpg?w=1024&fit=max&auto=format"
 },
 {
  "name": "Hannah Till",
  "hon": "",
  "dates": "1721–1826",
  "type": "Revolutionary Era",
  "section": "Lebanon",
  "lot": "316",
  "bio": "Patriot, American Revolutionary War",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Hannah_Archer_Till",
  "img": ""
 },
 {
  "name": "Destitute Colored Children",
  "hon": "",
  "dates": "d. ",
  "type": "Social Service Organization",
  "section": "Olive",
  "lot": "303",
  "bio": "Also lot(s): 304, 307, 308",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Association for the Care of Colored Orphans",
  "hon": "",
  "dates": "d. ",
  "type": "Social Service Organization",
  "section": "Olive",
  "lot": "298",
  "bio": "Also lot(s): 299, 300, 301",
  "mil": "",
  "link": "",
  "img": ""
 },
 {
  "name": "Edward Bolden",
  "hon": "",
  "dates": "1885–1950",
  "type": "Sports",
  "section": "Richard Allen",
  "lot": "906",
  "bio": "\"Ed\" Bolden — baseball executive in the Negro Baseball Leagues",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Ed_Bolden",
  "img": "https://upload.wikimedia.org/wikipedia/commons/0/01/Ed_Bolden_1924.jpg"
 },
 {
  "name": "George H. Cole",
  "hon": "",
  "dates": "1875–1923",
  "type": "Sports",
  "section": "David Bustill Bowser",
  "lot": "18",
  "bio": "Boxer, \"Pennsylvania's Terror\"",
  "mil": "",
  "link": "https://boxrec.com/wiki/index.php/George_Cole",
  "img": ""
 },
 {
  "name": "John Mott Drew",
  "hon": "",
  "dates": "1883–1977",
  "type": "Sports",
  "section": "Celestine",
  "lot": "1170",
  "bio": "Owner of a bus company and the Hilldale baseball team",
  "mil": "",
  "link": "https://www.newspapers.com/article/philadelphia-daily-news-john-mott-drew-s/42175343/?locale=en-US",
  "img": ""
 },
 {
  "name": "Tyrone Everett",
  "hon": "",
  "dates": "1853–1977",
  "type": "Sports",
  "section": "Frederick Douglass",
  "lot": "E 430",
  "bio": "Boxer, \"The Mean Machine\"",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Tyrone_Everett",
  "img": "https://upload.wikimedia.org/wikipedia/commons/3/30/Tyrone_Everett_in_World_Boxing_May_1976_issue.jpg"
 },
 {
  "name": "John Baxter Taylor",
  "hon": "Dr.",
  "dates": "1882–1916",
  "type": "Sports",
  "section": "Celestine",
  "lot": "166",
  "bio": "Track star, veterinarian; first African American Olympic gold medal winner",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/John_Taylor_(relay_runner)",
  "img": "https://upload.wikimedia.org/wikipedia/commons/b/bf/John_baxter_taylor.jpg"
 },
 {
  "name": "James J. G. Bias",
  "hon": "Dr.",
  "dates": "1807–1860",
  "type": "Underground Railroad",
  "section": "Lebanon",
  "lot": "157",
  "bio": "Clergyman, physician; Philadelphia Anti-Slavery Society; a founder of the Philadelphia Vigilance Committee",
  "mil": "",
  "link": "https://www.1838blackmetropolis.com/post/james-j-g-bias-and-eliza-bias-medical-care-and-social-support-for-freedom-seekers-in-1838",
  "img": ""
 },
 {
  "name": "Nathaniel W. Depee",
  "hon": "",
  "dates": "1812–1868",
  "type": "Underground Railroad",
  "section": "Lebanon",
  "lot": "653",
  "bio": "Underground Railroad leader. Also lot(s): 654. Also listed: (Lebanon)",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Nathaniel_W._Depee",
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Nathaniel_W._Depee%2C_1872.png"
 },
 {
  "name": "Grace A Mapps",
  "hon": "",
  "dates": "d. ",
  "type": "Underground Railroad",
  "section": "Lebanon",
  "lot": "727",
  "bio": "Mother of Sarah Mapps",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/Grace_A._Mapps",
  "img": ""
 },
 {
  "name": "Shepherd Shay",
  "hon": "",
  "dates": "d. ",
  "type": "Underground Railroad",
  "section": "Lebanon",
  "lot": "143",
  "bio": "Cloths dealer and early Underground Railroad Leader - Vigilance Committee",
  "mil": "",
  "link": "https://www.1838blackmetropolis.com/post/we-have-the-receipts-finding-underground-railroad-receipts-in-the-archives",
  "img": ""
 },
 {
  "name": "Stephen Smith",
  "hon": "Rev.",
  "dates": "1795–1873",
  "type": "Underground Railroad",
  "section": "Celestine",
  "lot": "1023",
  "bio": "Abolitionist; lumber and real estate magnate",
  "mil": "",
  "link": "https://coloredconventions.org/black-mobility/delegates/stephen-smith/",
  "img": ""
 },
 {
  "name": "William Still",
  "hon": "",
  "dates": "1821–1902",
  "type": "Underground Railroad",
  "section": "Lebanon",
  "lot": "16",
  "bio": "Father of the Underground Railroad",
  "mil": "",
  "link": "https://en.wikipedia.org/wiki/William_Still",
  "img": "https://upload.wikimedia.org/wikipedia/commons/5/5f/William_Still_abolitionist.jpg"
 },
 {
  "name": "Ulysses B. Vidal",
  "hon": "",
  "dates": "d. 1877",
  "type": "Underground Railroad",
  "section": "Olive",
  "lot": "203",
  "bio": "Underground Railroad Conductor, Accountant To Stephen Smith",
  "mil": "",
  "link": "https://coloredconventions.org/black-mobility/delegates/ulysses-b-vidal/",
  "img": ""
 }
];

export const CATEGORIES = ["Architecture","Art","Business","Church","Civil Rights","Civil Sector","Clergy","Divine Nine Founder","Education","Entertainment","Family","Fraternal","Historian","History","Journalism","Literature","Medicine","Military","Music","Politics","Revolutionary Era","Social Service Organization","Sports","Underground Railroad"];
